/**
 * DEAD O'CLOCK: The Halloween Massacre
 * Configuration & Localization Registry
 */

export const CONFIG = {
  TITLE: "DEAD O'CLOCK: The Halloween Massacre",
  VERSION: "1.0.0",
  INTERNAL_WIDTH: 320,
  INTERNAL_HEIGHT: 180,
  FOV: Math.PI / 3, // 60 degrees
  ASSET_BASE: "assets/",
  STORAGE_KEY_SAVE: "deadoclock_save_slot",
  STORAGE_KEY_SETTINGS: "deadoclock_settings",
  MAX_CORPSES: 40,
  RAY_COUNT: 320,
  TARGET_FPS: 60,
  MOUSE_SENSITIVITY_DEFAULT: 0.0025,
  AUDIO_VOLUME_DEFAULT: 0.7,
  GRAPHICS_QUALITY_DEFAULT: "high", // "low" or "high"
  TOUCH_ENABLED_DEFAULT: "auto",

  // Amiga 1200 AGA Inspired Palette
  PALETTE: {
    PURPLE_DEEP: "#180b2b",
    PURPLE_MID: "#3e1e68",
    PURPLE_BRIGHT: "#8b3fe8",
    BLUE_NIGHT: "#0d1b2a",
    BLUE_MOON: "#24426c",
    BLUE_CYAN: "#48cae4",
    GREEN_RITUAL: "#107e3e",
    GREEN_FLAME: "#39ff14",
    GREEN_SLIME: "#2dc653",
    ORANGE_PUMPKIN: "#d05b0c",
    ORANGE_FIRE: "#ff7b00",
    ORANGE_GLOW: "#ffa200",
    RED_BLOOD: "#780000",
    RED_ALERT: "#c1121f",
    RED_CRIMSON: "#ff2a2a",
    BROWN_WOOD: "#4a2810",
    BROWN_EARTH: "#2e1a09",
    GRAY_STONE: "#495057",
    GRAY_LIGHT: "#adb5bd",
    BLACK: "#050508",
    WHITE_BONE: "#e0dacf",
    YELLOW_EYES: "#ffea00"
  },

  WEAPONS: {
    AXE: {
      id: "axe",
      name: "Ascia Ruvida",
      ammoType: null,
      ammoPerShot: 0,
      damageMin: 35,
      damageMax: 60,
      range: 1.5,
      cooldown: 400,
      isMelee: true
    },
    PISTOL: {
      id: "pistol",
      name: "Rivoltella d'Argento",
      ammoType: "bullets",
      ammoPerShot: 1,
      damageMin: 18,
      damageMax: 30,
      range: 25,
      cooldown: 280,
      isMelee: false
    },
    SHOTGUN: {
      id: "shotgun",
      name: "Fucile a Pompa",
      ammoType: "shells",
      ammoPerShot: 1,
      pellets: 6,
      damageMin: 10,
      damageMax: 18,
      spread: 0.08,
      range: 18,
      cooldown: 650,
      isMelee: false
    },
    DOUBLE_SHOTGUN: {
      id: "double_shotgun",
      name: "Doppietta Infernale",
      ammoType: "shells",
      ammoPerShot: 2,
      pellets: 14,
      damageMin: 12,
      damageMax: 20,
      spread: 0.16,
      range: 14,
      cooldown: 950,
      isMelee: false
    },
    CROSSBOW: {
      id: "crossbow",
      name: "Balestra Gotica",
      ammoType: "occult",
      ammoPerShot: 1,
      damageMin: 80,
      damageMax: 140,
      range: 30,
      projectileSpeed: 16,
      cooldown: 500,
      isMelee: false,
      isProjectile: true
    }
  },

  PICKUPS: {
    HEALTH_VIAL: { type: "health", amount: 10, max: 100, label: "Fiala di Sangue vitale (+10)" },
    MEDKIT: { type: "health", amount: 25, max: 100, label: "Borsa Medica (+25)" },
    HEART_CRYSTAL: { type: "health_full", amount: 100, max: 100, label: "Cristallo del Cuore (Salute Massima!)" },
    ARMOR_SHARD: { type: "armor", amount: 10, max: 100, label: "Frammento d'Armatura (+10)" },
    ARMOR_FULL: { type: "armor_full", amount: 100, max: 100, label: "Armatura Completa (100 Corazza!)" },
    AMMO_MAGAZINE: { type: "bullets", amount: 12, max: 150, label: "Caricatore Argento (+12)" },
    AMMO_BOX: { type: "bullets", amount: 40, max: 150, label: "Scatola Munizioni (+40)" },
    AMMO_SHELLS: { type: "shells", amount: 8, max: 50, label: "Cartucce Fucile (+8)" },
    AMMO_OCCULT: { type: "occult", amount: 20, max: 80, label: "Cella Occulta (+20)" },
    KEY_BLUE: { type: "key", keyId: "blue", label: "Chiave del Corvo Blu raccolta!" },
    KEY_ORANGE: { type: "key", keyId: "orange", label: "Chiave Zucca Arancione raccolta!" },
    KEY_RED: { type: "key", keyId: "red", label: "Chiave Teschio Rossa raccolta!" },
    KEY_PURPLE: { type: "key", keyId: "purple", label: "Chiave dell'Orologio Viola raccolta!" }
  }
};

export const STRINGS = {
  it: {
    GAME_TITLE: "DEAD O'CLOCK",
    GAME_SUBTITLE: "The Halloween Massacre",
    START_GAME: "Nuova Partita",
    CONTINUE: "Continua",
    CONTROLS: "Comandi",
    SETTINGS: "Impostazioni",
    RESUME: "Riprendi Gioco",
    BACK_TO_MENU: "Torna al Menu",
    RESTART_LEVEL: "Ricomincia Livello",
    GAME_OVER: "L'ORA MORTA TI HA RECLAMATO",
    VICTORY_TITLE: "LA MALEDIZIONE È SPEZZATA!",
    VICTORY_SUBTITLE: "L'orologio segna l'alba del 1° Novembre. La notte di Halloween è finita.",
    LEVEL_CLEARED: "LIVELLO COMPLETATO!",
    KEY_REQUIRED_BLUE: "Serve la Chiave del Corvo Blu!",
    KEY_REQUIRED_ORANGE: "Serve la Chiave Zucca Arancione!",
    KEY_REQUIRED_RED: "Serve la Chiave Teschio Rossa!",
    KEY_REQUIRED_PURPLE: "Serve la Chiave dell'Orologio Viola!",
    DOOR_LOCKED: "Questa porta è sigillata ermeticamente.",
    SWITCH_ACTIVATED: "Un ingranaggio si muove in lontananza...",
    SECRET_FOUND: "SEGRETO SCOPERTO!",
    STATS_KILLS: "Nemici eliminati:",
    STATS_SECRETS: "Segreti scoperti:",
    STATS_TIME: "Tempo impiegato:",
    NEXT_LEVEL: "Prosegui nel Terrore",
    PAUSED: "PAUSA",
    HEALTH: "VITA",
    ARMOR: "CORAZZA",
    AMMO: "COLPI",
    WEAPON: "ARMA",
    KEYS: "CHIAVI",
    PRESS_USE: "Premi [E] o [SPAZIO] per interagire",
    CLICK_TO_PLAY: "CLICCA QUI PER GIOCARE (Pointer Lock)",
    TOUCH_JOYSTICK: "Movimento",
    TOUCH_LOOK: "Visuale",
    TOUCH_FIRE: "FUOCO",
    TOUCH_USE: "USA",
    TOUCH_WEAPON: "ARMA",
    TOUCH_PAUSE: "PAUSA",
    SETTINGS_VOLUME: "Volume Audio:",
    SETTINGS_SENS: "Sensibilità Mouse:",
    SETTINGS_QUALITY: "Qualità Grafica:",
    SETTINGS_TOUCH: "Controlli Touch:",
    SETTINGS_FULLSCREEN: "Schermo Intero",
    QUALITY_HIGH: "Alta (Soffitti/Pavimenti completi)",
    QUALITY_LOW: "Bassa (Prestazioni massime)",
    AUTO: "Automatico",
    ALWAYS_ON: "Sempre Attivi",
    ALWAYS_OFF: "Disattivati",
    L01_NAME: "IL BOSCO DELLA LUNA MORTA",
    L01_INTRO: "Halloween 1993. A mezzanotte, i rintocchi dell'Orologio Proibito risvegliano le tenebre. Attraversa la selva stregata, trova un'arma e raggiungi i cancelli del cimitero prima che sia troppo tardi.",
    L02_NAME: "IL CIMITERO DEI SENZA NOME",
    L02_INTRO: "Il cancello di ferro cigola. Mausolei fatiscenti e fosse scoperte brulicano di non-morti al servizio del Re Zucca. Trova la Chiave Zucca per spalancare l'ingresso alla Cripta sotterranea.",
    L03_NAME: "LA CRIPTA DELLE ORE",
    L03_INTRO: "Nei meandri della cripta, il freddo penetra nelle ossa. Distruggi i sigilli blasfemi, attraversa gli ingranaggi monumentali ed elimina il Cavaliere Senza Testa per ottenere la Chiave Teschio.",
    L04_NAME: "LE CATACOMBE DELL'ORA MORTA",
    L04_INTRO: "Le catacombe scorrono di sangue e fiamme fatue. Qui riposa Clock Reaper, il guardiano del tempo eterno. Distruggi la creatura per riavviare l'orologio e spezzare la maledizione!"
  }
};
